name: ðŸš€ Legal AI System - Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - staging
        - production

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '20'
  
jobs:
  # =============================================================================
  # SECURITY AND COMPLIANCE CHECKS
  # =============================================================================
  security-scan:
    name: ðŸ”’ Security & Compliance Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Run Semgrep SAST scan
      uses: semgrep/semgrep-action@v1
      with:
        config: >-
          p/security-audit
          p/python
          p/typescript
          p/docker
          p/kubernetes
        generateSarif: "1"

    - name: Upload Semgrep results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: semgrep.sarif

    - name: Check for hardcoded secrets
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD

  # =============================================================================
  # LEGAL AI BACKEND CI/CD
  # =============================================================================
  backend-ci:
    name: ðŸ Backend CI - Python/FastAPI
    runs-on: ubuntu-latest
    needs: [security-scan]
    
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_legal_ai
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libpq-dev \
          poppler-utils \
          tesseract-ocr \
          tesseract-ocr-eng \
          libreoffice

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install -r backend/requirements-dev.txt

    - name: Create test environment file
      run: |
        cat > backend/.env.test << EOF
        DATABASE_URL=postgresql://postgres:postgres@localhost:5432/test_legal_ai
        REDIS_URL=redis://localhost:6379/0
        CELERY_BROKER_URL=redis://localhost:6379/1
        CELERY_RESULT_BACKEND=redis://localhost:6379/1
        SECRET_KEY=test-secret-key-for-ci
        JWT_SECRET_KEY=test-jwt-secret-key-for-ci
        ENVIRONMENT=test
        DEBUG=true
        OPENAI_API_KEY=test-key
        ANTHROPIC_API_KEY=test-key
        EOF

    - name: Run database migrations
      working-directory: ./backend
      run: |
        export PYTHONPATH=$PWD
        alembic upgrade head

    - name: Run linting with flake8
      working-directory: ./backend
      run: |
        flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 app/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run type checking with mypy
      working-directory: ./backend
      run: |
        mypy app/ --ignore-missing-imports

    - name: Run security checks with bandit
      working-directory: ./backend
      run: |
        bandit -r app/ -f json -o bandit-report.json
        bandit -r app/ -ll

    - name: Run tests with pytest
      working-directory: ./backend
      run: |
        export PYTHONPATH=$PWD
        pytest tests/ \
          --cov=app \
          --cov-report=xml \
          --cov-report=html \
          --cov-report=term \
          --junit-xml=pytest-report.xml \
          -v

    - name: Run integration tests
      working-directory: ./backend
      run: |
        export PYTHONPATH=$PWD
        pytest tests/integration/ \
          --cov=app \
          --cov-append \
          --junit-xml=integration-report.xml \
          -v

    - name: Upload test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Backend Test Results
        path: 'backend/*-report.xml'
        reporter: java-junit

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage.xml
        flags: backend
        name: backend-coverage
        fail_ci_if_error: false

    - name: Archive test artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: backend-test-results
        path: |
          backend/coverage.xml
          backend/htmlcov/
          backend/*-report.xml
          backend/bandit-report.json

  # =============================================================================
  # LEGAL AI FRONTEND CI/CD
  # =============================================================================
  frontend-ci:
    name: âš›ï¸ Frontend CI - Next.js/TypeScript
    runs-on: ubuntu-latest
    needs: [security-scan]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Create test environment file
      working-directory: ./frontend
      run: |
        cat > .env.test << EOF
        NEXT_PUBLIC_API_URL=http://localhost:8000
        NEXT_PUBLIC_WS_URL=ws://localhost:8001
        NEXTAUTH_SECRET=test-nextauth-secret
        NEXTAUTH_URL=http://localhost:3000
        NODE_ENV=test
        EOF

    - name: Run ESLint
      working-directory: ./frontend
      run: |
        npm run lint
        npm run lint:fix

    - name: Run TypeScript type checking
      working-directory: ./frontend
      run: npm run typecheck

    - name: Run Prettier formatting check
      working-directory: ./frontend
      run: npm run format:check

    - name: Run unit tests
      working-directory: ./frontend
      run: |
        npm run test:coverage
        npm run test:ci

    - name: Run component tests with Storybook
      working-directory: ./frontend
      run: |
        npm run build-storybook
        npm run test:storybook:ci

    - name: Build application
      working-directory: ./frontend
      run: |
        npm run build
        
    - name: Export static site (for testing)
      working-directory: ./frontend
      run: npm run export

    - name: Run bundle analyzer
      working-directory: ./frontend
      run: npm run analyze

    - name: Upload test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Frontend Test Results
        path: 'frontend/test-results.xml'
        reporter: jest-junit

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./frontend/coverage/lcov.info
        flags: frontend
        name: frontend-coverage
        fail_ci_if_error: false

    - name: Archive test artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: frontend-test-results
        path: |
          frontend/coverage/
          frontend/test-results.xml
          frontend/.next/
          frontend/storybook-static/
          frontend/bundle-analysis/

  # =============================================================================
  # E2E TESTING WITH PLAYWRIGHT
  # =============================================================================
  e2e-tests:
    name: ðŸŽ­ End-to-End Tests
    runs-on: ubuntu-latest
    needs: [backend-ci, frontend-ci]
    
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_legal_ai
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Set up Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev poppler-utils tesseract-ocr

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Install Node.js dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Install Playwright browsers
      working-directory: ./frontend
      run: npx playwright install --with-deps

    - name: Create E2E test environment
      run: |
        cat > backend/.env.e2e << EOF
        DATABASE_URL=postgresql://postgres:postgres@localhost:5432/test_legal_ai
        REDIS_URL=redis://localhost:6379/0
        SECRET_KEY=e2e-test-secret
        JWT_SECRET_KEY=e2e-test-jwt-secret
        ENVIRONMENT=test
        DEBUG=true
        EOF
        
        cat > frontend/.env.e2e << EOF
        NEXT_PUBLIC_API_URL=http://localhost:8000
        NEXTAUTH_SECRET=e2e-test-nextauth-secret
        NEXTAUTH_URL=http://localhost:3000
        EOF

    - name: Setup test database
      working-directory: ./backend
      run: |
        export PYTHONPATH=$PWD
        alembic upgrade head
        python scripts/seed_test_data.py

    - name: Start backend server
      working-directory: ./backend
      run: |
        export PYTHONPATH=$PWD
        uvicorn main:app --host 0.0.0.0 --port 8000 &
        sleep 10
        curl -f http://localhost:8000/health || exit 1

    - name: Build and start frontend
      working-directory: ./frontend
      run: |
        npm run build
        npm start &
        sleep 15
        curl -f http://localhost:3000 || exit 1

    - name: Run Playwright E2E tests
      working-directory: ./frontend
      run: |
        npm run test:e2e

    - name: Upload Playwright report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: |
          frontend/playwright-report/
          frontend/test-results/

  # =============================================================================
  # BUILD SUMMARY AND NOTIFICATIONS
  # =============================================================================
  build-summary:
    name: ðŸ“Š Build Summary
    runs-on: ubuntu-latest
    needs: [security-scan, backend-ci, frontend-ci, e2e-tests]
    if: always()

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate build summary
      run: |
        echo "# ðŸš€ Legal AI System - Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Build Status" >> $GITHUB_STEP_SUMMARY
        echo "- **Security Scan**: ${{ needs.security-scan.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Backend CI**: ${{ needs.backend-ci.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Frontend CI**: ${{ needs.frontend-ci.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- **E2E Tests**: ${{ needs.e2e-tests.result }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Commit Information" >> $GITHUB_STEP_SUMMARY
        echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Author**: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Workflow**: ${{ github.workflow }}" >> $GITHUB_STEP_SUMMARY

    - name: Notify Slack on failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        channel: '#legal-ai-alerts'
        fields: repo,message,commit,author,action,eventName,ref,workflow
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Notify Slack on success
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: success
        channel: '#legal-ai-deployments'
        fields: repo,message,commit,author,action,eventName,ref,workflow
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}