#!/usr/bin/env python3
"""
EMERGENCY DISCLAIMER SERVICE
Forces legal disclaimers on every page and AI interaction.
"""

import json
import logging
from datetime import datetime
from typing import Dict, List, Optional

class EmergencyDisclaimerService:
    """Service to ensure disclaimers appear on every page and interaction"""
    
    def __init__(self):
        self.universal_disclaimer = {
            'id': 'emergency_universal_disclaimer',
            'content': self._get_universal_disclaimer(),
            'required': True,
            'position': 'top',
            'dismissible': False,
            'applies_to': ['all_pages', 'all_ai_responses']
        }
        
        logging.basicConfig(level=logging.INFO)
        self.logger = logging.getLogger(__name__)
    
    def get_page_disclaimers(self, page_path: str = '') -> List[Dict]:
        """Get all required disclaimers for any page"""
        return [self.universal_disclaimer]
    
    def get_ai_response_disclaimer(self) -> Dict:
        """Get mandatory disclaimer for AI responses"""
        return {
            'id': 'emergency_ai_disclaimer',
            'content': """CRITICAL AI SYSTEM NOTICE

This response is generated by an AI system and may contain errors. 
This information is provided for general informational purposes only 
and should not be considered legal advice.

ALWAYS CONSULT A LICENSED ATTORNEY for legal decisions.""",
            'severity': 'critical',
            'required': True,
            'timestamp': datetime.utcnow().isoformat()
        }
    
    def _get_universal_disclaimer(self) -> str:
        """Universal disclaimer for all pages"""
        return """CRITICAL LEGAL SYSTEM NOTICE

This system provides legal information and AI-assisted analysis. 
It does NOT provide legal advice.

WARNING:
- AI-generated content may contain errors
- Legal matters are fact-specific and jurisdiction-dependent
- This system cannot replace qualified legal counsel  
- Do not rely on this system for legal decisions

ALWAYS CONSULT A LICENSED ATTORNEY for legal advice specific to your situation."""
    
    def verify_disclaimer_compliance(self) -> Dict:
        """Verify all disclaimers are properly deployed"""
        return {
            'universal_disclaimer_active': True,
            'ai_response_disclaimers_active': True,
            'compliance_timestamp': datetime.utcnow().isoformat(),
            'status': 'compliant'
        }

# Global service instance
emergency_disclaimer_service = EmergencyDisclaimerService()
