'use client';

import React, { useState, useCallback, useRef } from 'react';
import {
  Upload,
  FileText,
  CheckCircle,
  AlertCircle,
  X,
  Download,
  ChevronRight,
  Info,
  Eye,
  Star,
  Clock,
  DollarSign,
  Users,
  Scale,
  Shield
} from 'lucide-react';

import DisclaimerBanner from '@/components/compliance/DisclaimerBanner';
import ConfidenceScore from '@/components/compliance/ConfidenceScore';
import {
  DisclaimerType,
  DisclaimerDisplayFormat,
  type DisclaimerConfig
} from '@/types/legal-compliance';

// Types for our document intake flow
interface DocumentFile {
  file: File;
  id: string;
  progress: number;
  status: 'uploading' | 'analyzing' | 'completed' | 'error';
}

interface AnalysisResult {
  analysisId: string;
  documentType: {
    category: string;
    confidence: number;
    subcategory?: string;
  };
  extractedEntities: Array<{
    entityType: string;
    value: string;
    confidence: number;
    location: string;
  }>;
  informationGaps: Array<{
    gapType: string;
    description: string;
    severity: string;
  }>;
  questions: Array<{
    questionId: string;
    questionText: string;
    inputType: string;
    whyNeeded: string;
    options?: Array<{
      value: string;
      label: string;
    }>;
  }>;
  complianceStatus: {
    hasAdvice: boolean;
    complianceScore: number;
  };
}

interface Strategy {
  strategyId: string;
  name: string;
  description: string;
  strategyType: string;
  commonAdvantages: string[];
  typicalChallenges: string[];
  generalTimeline: string;
  estimatedCostRange: string;
  complexityLevel: string;
  applicableScenarios: string[];
  disclaimerText: string;
}

interface StrategyResponse {
  matterId: string;
  strategies: Strategy[];
  generatedAt: string;
  educationalDisclaimer: string;
  complianceValidated: boolean;
}

const IntelligentIntakePage: React.FC = () => {
  // State management
  const [currentStep, setCurrentStep] = useState<'upload' | 'analysis' | 'questions' | 'strategies'>('upload');
  const [uploadedFile, setUploadedFile] = useState<DocumentFile | null>(null);
  const [analysisResult, setAnalysisResult] = useState<AnalysisResult | null>(null);
  const [questionAnswers, setQuestionAnswers] = useState<Record<string, any>>({});
  const [strategies, setStrategies] = useState<StrategyResponse | null>(null);
  const [selectedStrategy, setSelectedStrategy] = useState<Strategy | null>(null);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isDragOver, setIsDragOver] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);

  // Disclaimer configurations
  const mainDisclaimer: DisclaimerConfig = {
    id: 'intelligent_intake_main',
    type: DisclaimerType.NO_LEGAL_ADVICE,
    title: 'Educational Document Analysis Only',
    content: '<strong>IMPORTANT:</strong> This system provides educational document analysis and information about common legal options. No legal advice is provided. No attorney-client relationship is created. Consult qualified legal counsel for advice specific to your situation.',
    displayFormat: DisclaimerDisplayFormat.HEADER_BANNER,
    isRequired: true,
    showForRoles: [],
    context: ['document_intake'],
    priority: 1,
    isActive: true,
    requiresAcknowledgment: true,
    acknowledgeButtonText: 'I Understand',
    dismissible: false,
  };

  const analysisDisclaimer: DisclaimerConfig = {
    id: 'analysis_results_disclaimer',
    type: DisclaimerType.AI_LIMITATION,
    title: 'AI Analysis Limitations',
    content: 'Document analysis results are generated by AI and are for educational purposes only. Results may not be complete or accurate. Professional review is recommended.',
    displayFormat: DisclaimerDisplayFormat.INLINE_TEXT,
    isRequired: false,
    showForRoles: [],
    context: ['analysis_results'],
    priority: 2,
    isActive: true,
    requiresAcknowledgment: false,
    dismissible: true,
  };

  const strategyDisclaimer: DisclaimerConfig = {
    id: 'strategy_information_disclaimer',
    type: DisclaimerType.NO_LEGAL_ADVICE,
    title: 'Strategy Information Only',
    content: 'Strategy information presented is educational only and describes common legal options. This does not constitute legal advice or recommendations. Each situation is unique and requires professional legal consultation.',
    displayFormat: DisclaimerDisplayFormat.INLINE_TEXT,
    isRequired: true,
    showForRoles: [],
    context: ['strategy_information'],
    priority: 1,
    isActive: true,
    requiresAcknowledgment: true,
    acknowledgeButtonText: 'Understood',
    dismissible: false,
  };

  // File upload handlers
  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(true);
  }, []);

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(false);
  }, []);

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(false);

    const files = Array.from(e.dataTransfer.files);
    if (files.length > 0) {
      handleFileSelect(files[0]);
    }
  }, []);

  const handleFileSelect = useCallback((file: File) => {
    // Validate file type
    const allowedTypes = ['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain'];

    if (!allowedTypes.includes(file.type)) {
      setError('Please upload a PDF, Word document, or text file.');
      return;
    }

    // Validate file size (10MB limit)
    if (file.size > 10 * 1024 * 1024) {
      setError('File size must be less than 10MB.');
      return;
    }

    const documentFile: DocumentFile = {
      file,
      id: Date.now().toString(),
      progress: 0,
      status: 'uploading'
    };

    setUploadedFile(documentFile);
    setError(null);
    uploadDocument(documentFile);
  }, []);

  const uploadDocument = async (documentFile: DocumentFile) => {
    setIsLoading(true);

    try {
      // Simulate file upload progress
      for (let progress = 0; progress <= 100; progress += 10) {
        setUploadedFile(prev => prev ? { ...prev, progress } : null);
        await new Promise(resolve => setTimeout(resolve, 100));
      }

      setUploadedFile(prev => prev ? { ...prev, status: 'analyzing' } : null);

      // Mock API call for document analysis
      await new Promise(resolve => setTimeout(resolve, 2000));

      // Mock analysis result
      const mockAnalysisResult: AnalysisResult = {
        analysisId: 'analysis_' + Date.now(),
        documentType: {
          category: 'bankruptcy_petition',
          confidence: 0.87,
          subcategory: 'chapter_7_voluntary'
        },
        extractedEntities: [
          {
            entityType: 'debtor_name',
            value: 'Sample Business LLC',
            confidence: 0.95,
            location: 'Line 5'
          },
          {
            entityType: 'business_address',
            value: '123 Main St, City, ST 12345',
            confidence: 0.88,
            location: 'Line 8-9'
          },
          {
            entityType: 'tax_id',
            value: '12-3456789',
            confidence: 0.92,
            location: 'Line 12'
          }
        ],
        informationGaps: [
          {
            gapType: 'debt_amount',
            description: 'Total debt amount not specified in document',
            severity: 'high'
          },
          {
            gapType: 'creditor_types',
            description: 'Types of creditors not clearly identified',
            severity: 'medium'
          },
          {
            gapType: 'asset_info',
            description: 'Asset information incomplete',
            severity: 'medium'
          }
        ],
        questions: [
          {
            questionId: 'debt_total_001',
            questionText: 'What is your total unsecured debt amount?',
            inputType: 'currency',
            whyNeeded: 'Total debt amount helps determine bankruptcy chapter eligibility and required documentation.',
            options: []
          },
          {
            questionId: 'creditor_types_001',
            questionText: 'What types of creditors do you owe money to?',
            inputType: 'multiselect',
            whyNeeded: 'Different creditor types have different rights and priorities in bankruptcy proceedings.',
            options: [
              { value: 'credit_cards', label: 'Credit Card Companies' },
              { value: 'medical', label: 'Medical Providers' },
              { value: 'utilities', label: 'Utility Companies' },
              { value: 'banks', label: 'Banks/Financial Institutions' },
              { value: 'suppliers', label: 'Business Suppliers' }
            ]
          },
          {
            questionId: 'monthly_income_001',
            questionText: 'What is your current gross monthly income from all sources?',
            inputType: 'currency',
            whyNeeded: 'Income information determines means test eligibility and affects bankruptcy chapter options.',
            options: []
          }
        ],
        complianceStatus: {
          hasAdvice: false,
          complianceScore: 1.0
        }
      };

      setAnalysisResult(mockAnalysisResult);
      setUploadedFile(prev => prev ? { ...prev, status: 'completed' } : null);
      setCurrentStep('analysis');

    } catch (err) {
      setError('Failed to analyze document. Please try again.');
      setUploadedFile(prev => prev ? { ...prev, status: 'error' } : null);
    } finally {
      setIsLoading(false);
    }
  };

  const handleQuestionAnswer = (questionId: string, answer: any) => {
    setQuestionAnswers(prev => ({
      ...prev,
      [questionId]: answer
    }));
  };

  const handleSubmitAnswers = async () => {
    if (!analysisResult) return;

    setIsLoading(true);
    try {
      // Mock API call to submit answers
      await new Promise(resolve => setTimeout(resolve, 1000));

      // Mock strategy generation
      const mockStrategies: StrategyResponse = {
        matterId: 'matter_' + Date.now(),
        strategies: [
          {
            strategyId: 'ch7_strategy_001',
            name: 'Chapter 7 Bankruptcy Information',
            description: 'Chapter 7 is a liquidation proceeding where parties typically discharge eligible debts. Non-exempt assets are commonly sold to pay creditors.',
            strategyType: 'bankruptcy_chapter_7',
            commonAdvantages: [
              'Parties typically receive discharge of most unsecured debts',
              'Process generally takes 4-6 months to complete',
              'Fresh start commonly available for individuals and businesses',
              'Automatic stay typically provides immediate creditor relief',
              'Many parties find this option less expensive than reorganization'
            ],
            typicalChallenges: [
              'Non-exempt assets are typically subject to liquidation',
              'Some debts commonly remain non-dischargeable',
              'Business operations generally cease during the process',
              'Parties typically cannot choose which debts to discharge',
              'Credit impact commonly lasts 7-10 years'
            ],
            generalTimeline: '4-6 months',
            estimatedCostRange: 'Attorneys typically charge $1,500-$4,000 for Chapter 7 cases, plus court filing fees of approximately $335',
            complexityLevel: 'Medium',
            applicableScenarios: [
              'Parties with primarily unsecured debt',
              'Businesses ceasing operations',
              'Individuals seeking fresh start',
              'Cases where assets are minimal or fully exempt'
            ],
            disclaimerText: 'Common legal option. Attorney can advise if applicable. This information is educational only and does not constitute legal advice.'
          },
          {
            strategyId: 'workout_strategy_001',
            name: 'Out-of-Court Workout Information',
            description: 'An out-of-court workout involves voluntary negotiations between parties and creditors to restructure debt obligations without formal bankruptcy proceedings.',
            strategyType: 'out_of_court_workout',
            commonAdvantages: [
              'Parties typically avoid bankruptcy court costs and fees',
              'Process is commonly more confidential than court proceedings',
              'Timeline is typically more flexible and faster',
              'Business operations generally continue without court oversight',
              'Credit impact is commonly less severe than bankruptcy',
              'Parties typically retain full control over business decisions'
            ],
            typicalChallenges: [
              'Success commonly requires cooperation from all significant creditors',
              'No automatic stay typically protects against collection actions',
              'Holdout creditors commonly can disrupt the process',
              'Agreements typically require individual negotiation with each creditor',
              'Tax consequences commonly differ from bankruptcy treatment',
              'No discharge typically available for remaining obligations'
            ],
            generalTimeline: '2-6 months',
            estimatedCostRange: 'Costs typically range from $5,000-$50,000 in professional fees, generally lower than formal bankruptcy',
            complexityLevel: 'Simple',
            applicableScenarios: [
              'Temporary financial difficulties with viable long-term prospects',
              'Limited number of cooperative creditors',
              'Situations where privacy and confidentiality are priorities',
              'Cases where bankruptcy stigma could harm business relationships'
            ],
            disclaimerText: 'Common legal option. Attorney can advise if applicable. This information is educational only and does not constitute legal advice.'
          }
        ],
        generatedAt: new Date().toISOString(),
        educationalDisclaimer: 'All strategies are educational information only. No legal advice is provided. Consult qualified legal counsel for guidance specific to your situation.',
        complianceValidated: true
      };

      setStrategies(mockStrategies);
      setCurrentStep('strategies');

    } catch (err) {
      setError('Failed to generate strategies. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  const resetFlow = () => {
    setCurrentStep('upload');
    setUploadedFile(null);
    setAnalysisResult(null);
    setQuestionAnswers({});
    setStrategies(null);
    setSelectedStrategy(null);
    setError(null);
  };

  const openStrategyModal = (strategy: Strategy) => {
    setSelectedStrategy(strategy);
    setIsModalOpen(true);
  };

  const closeStrategyModal = () => {
    setIsModalOpen(false);
    setSelectedStrategy(null);
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Main Disclaimer */}
      <DisclaimerBanner disclaimer={mainDisclaimer} />

      <div className="max-w-6xl mx-auto py-8 px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-4">
            Intelligent Document Intake
          </h1>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Upload your legal document for educational analysis and explore common strategy options.
            All content is for informational purposes only.
          </p>
        </div>

        {/* Progress Steps */}
        <div className="flex justify-center mb-8">
          <nav className="flex space-x-4">
            {[
              { key: 'upload', label: 'Upload', icon: Upload },
              { key: 'analysis', label: 'Analysis', icon: FileText },
              { key: 'questions', label: 'Questions', icon: AlertCircle },
              { key: 'strategies', label: 'Strategies', icon: Scale }
            ].map((step, index) => {
              const Icon = step.icon;
              const isActive = currentStep === step.key;
              const isCompleted = ['upload', 'analysis', 'questions', 'strategies'].indexOf(currentStep) > index;

              return (
                <div
                  key={step.key}
                  className={`flex items-center px-4 py-2 rounded-lg ${
                    isActive
                      ? 'bg-blue-100 text-blue-700 border border-blue-200'
                      : isCompleted
                      ? 'bg-green-100 text-green-700 border border-green-200'
                      : 'bg-gray-100 text-gray-500 border border-gray-200'
                  }`}
                >
                  <Icon className="h-5 w-5 mr-2" />
                  <span className="font-medium">{step.label}</span>
                  {isCompleted && <CheckCircle className="h-4 w-4 ml-2 text-green-600" />}
                </div>
              );
            })}
          </nav>
        </div>

        {/* Error Display */}
        {error && (
          <div className="bg-red-50 border border-red-200 rounded-lg p-4 mb-6">
            <div className="flex">
              <AlertCircle className="h-5 w-5 text-red-500 mr-3 mt-0.5 flex-shrink-0" />
              <div>
                <p className="text-red-800">{error}</p>
                <button
                  onClick={() => setError(null)}
                  className="mt-2 text-red-600 hover:text-red-800 text-sm font-medium"
                >
                  Dismiss
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Content Based on Current Step */}
        {currentStep === 'upload' && (
          <div className="bg-white rounded-lg shadow-lg p-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-6 text-center">
              Upload Legal Document
            </h2>

            <div
              className={`
                border-2 border-dashed rounded-lg p-8 text-center
                transition-colors duration-200 cursor-pointer
                ${isDragOver
                  ? 'border-blue-400 bg-blue-50'
                  : 'border-gray-300 hover:border-blue-400 hover:bg-gray-50'
                }
              `}
              onDragOver={handleDragOver}
              onDragLeave={handleDragLeave}
              onDrop={handleDrop}
              onClick={() => fileInputRef.current?.click()}
            >
              <input
                ref={fileInputRef}
                type="file"
                multiple
                className="hidden"
                accept=".pdf,.doc,.docx,.txt"
                onChange={(e) => {
                  const file = e.target.files?.[0];
                  if (file) handleFileSelect(file);
                }}
              />

              <Upload className="h-12 w-12 text-gray-400 mx-auto mb-4" />
              <h3 className="text-lg font-medium text-gray-900 mb-2">
                Drop your document here
              </h3>
              <p className="text-gray-500 mb-4">
                or click to select a file
              </p>
              <p className="text-sm text-gray-400">
                Supports PDF, Word documents, and text files up to 10MB
              </p>
            </div>

            {uploadedFile && (
              <div className="mt-6 bg-gray-50 rounded-lg p-4">
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center">
                    <FileText className="h-5 w-5 text-gray-500 mr-2" />
                    <span className="text-sm font-medium text-gray-900">
                      {uploadedFile.file.name}
                    </span>
                  </div>
                  <button
                    onClick={() => setUploadedFile(null)}
                    className="text-gray-400 hover:text-gray-600"
                  >
                    <X className="h-4 w-4" />
                  </button>
                </div>

                {uploadedFile.status === 'uploading' && (
                  <div className="w-full bg-gray-200 rounded-full h-2">
                    <div
                      className="bg-blue-500 h-2 rounded-full transition-all duration-300"
                      style={{ width: `${uploadedFile.progress}%` }}
                    />
                  </div>
                )}

                {uploadedFile.status === 'analyzing' && (
                  <div className="flex items-center text-blue-600">
                    <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-blue-600 mr-2" />
                    <span className="text-sm">Analyzing document...</span>
                  </div>
                )}

                {uploadedFile.status === 'completed' && (
                  <div className="flex items-center text-green-600">
                    <CheckCircle className="h-4 w-4 mr-2" />
                    <span className="text-sm">Analysis completed</span>
                  </div>
                )}

                {uploadedFile.status === 'error' && (
                  <div className="flex items-center text-red-600">
                    <AlertCircle className="h-4 w-4 mr-2" />
                    <span className="text-sm">Analysis failed</span>
                  </div>
                )}
              </div>
            )}
          </div>
        )}

        {currentStep === 'analysis' && analysisResult && (
          <div className="space-y-6">
            {/* Analysis Disclaimer */}
            <DisclaimerBanner disclaimer={analysisDisclaimer} />

            <div className="bg-white rounded-lg shadow-lg p-8">
              <div className="flex items-center justify-between mb-6">
                <h2 className="text-2xl font-semibold text-gray-900">
                  Document Analysis Results
                </h2>
                <button
                  onClick={() => setCurrentStep('questions')}
                  className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 flex items-center"
                >
                  Continue to Questions
                  <ChevronRight className="h-4 w-4 ml-2" />
                </button>
              </div>

              {/* Document Type */}
              <div className="bg-blue-50 rounded-lg p-6 mb-6">
                <h3 className="text-lg font-semibold text-blue-900 mb-3">
                  Document Type Identified
                </h3>
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-blue-800 font-medium capitalize">
                      {analysisResult.documentType.category.replace('_', ' ')}
                      {analysisResult.documentType.subcategory && (
                        <span className="text-blue-600 ml-2">
                          ({analysisResult.documentType.subcategory.replace('_', ' ')})
                        </span>
                      )}
                    </p>
                    <p className="text-blue-600 text-sm mt-1">
                      Educational classification for analysis purposes
                    </p>
                  </div>
                  <ConfidenceScore
                    score={analysisResult.documentType.confidence}
                    variant="badge"
                    size="lg"
                  />
                </div>
              </div>

              {/* Extracted Information */}
              <div className="grid md:grid-cols-2 gap-6 mb-6">
                <div className="bg-green-50 rounded-lg p-6">
                  <h3 className="text-lg font-semibold text-green-900 mb-4 flex items-center">
                    <CheckCircle className="h-5 w-5 mr-2" />
                    Information Found
                  </h3>
                  <div className="space-y-3">
                    {analysisResult.extractedEntities.map((entity, index) => (
                      <div key={index} className="flex items-center justify-between">
                        <div>
                          <p className="text-green-800 font-medium capitalize">
                            {entity.entityType.replace('_', ' ')}: {entity.value}
                          </p>
                          <p className="text-green-600 text-xs">
                            Found at: {entity.location}
                          </p>
                        </div>
                        <ConfidenceScore
                          score={entity.confidence}
                          variant="badge"
                          size="sm"
                        />
                      </div>
                    ))}
                  </div>
                </div>

                <div className="bg-yellow-50 rounded-lg p-6">
                  <h3 className="text-lg font-semibold text-yellow-900 mb-4 flex items-center">
                    <AlertCircle className="h-5 w-5 mr-2" />
                    Information Gaps
                  </h3>
                  <div className="space-y-3">
                    {analysisResult.informationGaps.map((gap, index) => (
                      <div key={index}>
                        <div className="flex items-center justify-between mb-1">
                          <p className="text-yellow-800 font-medium capitalize">
                            {gap.gapType.replace('_', ' ')}
                          </p>
                          <span className={`px-2 py-1 rounded text-xs font-medium ${
                            gap.severity === 'high'
                              ? 'bg-red-100 text-red-700'
                              : gap.severity === 'medium'
                              ? 'bg-yellow-100 text-yellow-700'
                              : 'bg-gray-100 text-gray-700'
                          }`}>
                            {gap.severity}
                          </span>
                        </div>
                        <p className="text-yellow-700 text-sm">{gap.description}</p>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              {/* Compliance Status */}
              <div className="bg-gray-50 rounded-lg p-6">
                <h3 className="text-lg font-semibold text-gray-900 mb-3 flex items-center">
                  <Shield className="h-5 w-5 mr-2" />
                  Compliance Status
                </h3>
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-gray-700">
                      <strong>UPL Compliance:</strong> {analysisResult.complianceStatus.hasAdvice ? 'Review Required' : 'Compliant'}
                    </p>
                    <p className="text-gray-600 text-sm mt-1">
                      All content reviewed for educational compliance
                    </p>
                  </div>
                  <ConfidenceScore
                    score={analysisResult.complianceStatus.complianceScore}
                    label="Compliance Score"
                    variant="detailed"
                    size="sm"
                  />
                </div>
              </div>
            </div>
          </div>
        )}

        {currentStep === 'questions' && analysisResult && (
          <div className="bg-white rounded-lg shadow-lg p-8">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-2xl font-semibold text-gray-900">
                Complete Information Gathering
              </h2>
              <button
                onClick={handleSubmitAnswers}
                disabled={isLoading || Object.keys(questionAnswers).length === 0}
                className="bg-blue-600 text-white px-6 py-3 rounded-lg hover:bg-blue-700 disabled:bg-gray-400 disabled:cursor-not-allowed flex items-center"
              >
                {isLoading ? (
                  <>
                    <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2" />
                    Generating Strategies...
                  </>
                ) : (
                  <>
                    Generate Strategy Information
                    <ChevronRight className="h-4 w-4 ml-2" />
                  </>
                )}
              </button>
            </div>

            <div className="bg-blue-50 rounded-lg p-4 mb-6">
              <div className="flex items-start">
                <Info className="h-5 w-5 text-blue-500 mr-3 mt-0.5 flex-shrink-0" />
                <div>
                  <p className="text-blue-800 font-medium">Educational Information Gathering</p>
                  <p className="text-blue-700 text-sm mt-1">
                    These questions help provide more relevant educational content about common legal options.
                    Your responses are used for informational purposes only and do not constitute legal consultation.
                  </p>
                </div>
              </div>
            </div>

            <div className="space-y-6">
              {analysisResult.questions.map((question, index) => (
                <div key={question.questionId} className="border border-gray-200 rounded-lg p-6">
                  <div className="mb-4">
                    <h3 className="text-lg font-medium text-gray-900 mb-2">
                      {question.questionText}
                    </h3>
                    <p className="text-gray-600 text-sm bg-gray-50 rounded p-3">
                      <strong>Why this helps:</strong> {question.whyNeeded}
                    </p>
                  </div>

                  {question.inputType === 'currency' && (
                    <div>
                      <input
                        type="text"
                        placeholder="$0.00"
                        className="block w-full border border-gray-300 rounded-lg px-4 py-2 focus:ring-blue-500 focus:border-blue-500"
                        onChange={(e) => handleQuestionAnswer(question.questionId, e.target.value)}
                      />
                    </div>
                  )}

                  {question.inputType === 'multiselect' && question.options && (
                    <div className="space-y-2">
                      {question.options.map((option) => (
                        <label key={option.value} className="flex items-center">
                          <input
                            type="checkbox"
                            className="rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                            onChange={(e) => {
                              const currentAnswers = questionAnswers[question.questionId] || [];
                              const newAnswers = e.target.checked
                                ? [...currentAnswers, option.value]
                                : currentAnswers.filter((v: string) => v !== option.value);
                              handleQuestionAnswer(question.questionId, newAnswers);
                            }}
                          />
                          <span className="ml-2 text-gray-700">{option.label}</span>
                        </label>
                      ))}
                    </div>
                  )}

                  <div className="mt-3 text-xs text-gray-500">
                    Educational purposes only - Not legal consultation
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {currentStep === 'strategies' && strategies && (
          <div className="space-y-6">
            {/* Strategy Disclaimer */}
            <DisclaimerBanner disclaimer={strategyDisclaimer} />

            <div className="bg-white rounded-lg shadow-lg p-8">
              <div className="flex items-center justify-between mb-6">
                <div>
                  <h2 className="text-2xl font-semibold text-gray-900 mb-2">
                    Common Legal Strategy Options
                  </h2>
                  <p className="text-gray-600">
                    Educational information about common approaches in similar situations
                  </p>
                </div>
                <button
                  onClick={resetFlow}
                  className="bg-gray-600 text-white px-4 py-2 rounded-lg hover:bg-gray-700"
                >
                  Start New Analysis
                </button>
              </div>

              <div className="grid gap-6 lg:grid-cols-2">
                {strategies.strategies.map((strategy) => (
                  <div key={strategy.strategyId} className="border border-gray-200 rounded-lg p-6 hover:shadow-md transition-shadow">
                    <div className="flex items-start justify-between mb-4">
                      <div>
                        <h3 className="text-xl font-semibold text-gray-900 mb-2">
                          {strategy.name}
                        </h3>
                        <div className="flex items-center space-x-4 text-sm text-gray-600">
                          <div className="flex items-center">
                            <Clock className="h-4 w-4 mr-1" />
                            {strategy.generalTimeline}
                          </div>
                          <div className="flex items-center">
                            <Star className="h-4 w-4 mr-1" />
                            {strategy.complexityLevel}
                          </div>
                        </div>
                      </div>
                    </div>

                    <p className="text-gray-700 mb-4 line-clamp-3">
                      {strategy.description}
                    </p>

                    <div className="grid grid-cols-2 gap-4 mb-4">
                      <div>
                        <h4 className="font-medium text-green-700 mb-2">Common Advantages</h4>
                        <ul className="text-sm text-gray-600 space-y-1">
                          {strategy.commonAdvantages.slice(0, 2).map((advantage, index) => (
                            <li key={index} className="flex items-start">
                              <CheckCircle className="h-3 w-3 text-green-500 mr-1 mt-0.5 flex-shrink-0" />
                              <span className="line-clamp-2">{advantage}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                      <div>
                        <h4 className="font-medium text-orange-700 mb-2">Typical Challenges</h4>
                        <ul className="text-sm text-gray-600 space-y-1">
                          {strategy.typicalChallenges.slice(0, 2).map((challenge, index) => (
                            <li key={index} className="flex items-start">
                              <AlertCircle className="h-3 w-3 text-orange-500 mr-1 mt-0.5 flex-shrink-0" />
                              <span className="line-clamp-2">{challenge}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    </div>

                    <div className="bg-gray-50 rounded-lg p-3 mb-4">
                      <div className="flex items-center text-sm text-gray-600">
                        <DollarSign className="h-4 w-4 mr-1" />
                        <span className="line-clamp-2">{strategy.estimatedCostRange}</span>
                      </div>
                    </div>

                    <div className="flex justify-between items-center">
                      <div className="text-xs text-gray-500">
                        Educational information only
                      </div>
                      <button
                        onClick={() => openStrategyModal(strategy)}
                        className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 flex items-center text-sm"
                      >
                        <Eye className="h-4 w-4 mr-1" />
                        View Details
                      </button>
                    </div>
                  </div>
                ))}
              </div>

              <div className="mt-8 bg-yellow-50 border border-yellow-200 rounded-lg p-6">
                <div className="flex items-start">
                  <AlertCircle className="h-6 w-6 text-yellow-500 mr-3 mt-0.5 flex-shrink-0" />
                  <div>
                    <h3 className="font-semibold text-yellow-800 mb-2">Important Reminder</h3>
                    <p className="text-yellow-700 text-sm">
                      {strategies.educationalDisclaimer}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Strategy Detail Modal */}
      {isModalOpen && selectedStrategy && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-lg max-w-4xl w-full max-h-screen overflow-y-auto">
            <div className="p-6 border-b border-gray-200">
              <div className="flex items-center justify-between">
                <h2 className="text-2xl font-semibold text-gray-900">
                  {selectedStrategy.name}
                </h2>
                <button
                  onClick={closeStrategyModal}
                  className="text-gray-400 hover:text-gray-600"
                >
                  <X className="h-6 w-6" />
                </button>
              </div>
              <div className="mt-2 flex items-center space-x-4 text-sm text-gray-600">
                <div className="flex items-center">
                  <Clock className="h-4 w-4 mr-1" />
                  Timeline: {selectedStrategy.generalTimeline}
                </div>
                <div className="flex items-center">
                  <Star className="h-4 w-4 mr-1" />
                  Complexity: {selectedStrategy.complexityLevel}
                </div>
              </div>
            </div>

            <div className="p-6 space-y-6">
              <div>
                <h3 className="text-lg font-semibold text-gray-900 mb-3">Overview</h3>
                <p className="text-gray-700">{selectedStrategy.description}</p>
              </div>

              <div className="grid md:grid-cols-2 gap-6">
                <div>
                  <h3 className="text-lg font-semibold text-green-700 mb-3 flex items-center">
                    <CheckCircle className="h-5 w-5 mr-2" />
                    Common Advantages
                  </h3>
                  <ul className="space-y-2">
                    {selectedStrategy.commonAdvantages.map((advantage, index) => (
                      <li key={index} className="flex items-start">
                        <CheckCircle className="h-4 w-4 text-green-500 mr-2 mt-0.5 flex-shrink-0" />
                        <span className="text-gray-700">{advantage}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                <div>
                  <h3 className="text-lg font-semibold text-orange-700 mb-3 flex items-center">
                    <AlertCircle className="h-5 w-5 mr-2" />
                    Typical Challenges
                  </h3>
                  <ul className="space-y-2">
                    {selectedStrategy.typicalChallenges.map((challenge, index) => (
                      <li key={index} className="flex items-start">
                        <AlertCircle className="h-4 w-4 text-orange-500 mr-2 mt-0.5 flex-shrink-0" />
                        <span className="text-gray-700">{challenge}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              <div>
                <h3 className="text-lg font-semibold text-blue-700 mb-3 flex items-center">
                  <DollarSign className="h-5 w-5 mr-2" />
                  Cost Information
                </h3>
                <p className="text-gray-700 bg-blue-50 rounded-lg p-4">
                  {selectedStrategy.estimatedCostRange}
                </p>
              </div>

              <div>
                <h3 className="text-lg font-semibold text-purple-700 mb-3 flex items-center">
                  <Users className="h-5 w-5 mr-2" />
                  Applicable Scenarios
                </h3>
                <ul className="grid md:grid-cols-2 gap-2">
                  {selectedStrategy.applicableScenarios.map((scenario, index) => (
                    <li key={index} className="flex items-start">
                      <div className="h-2 w-2 bg-purple-500 rounded-full mr-2 mt-2 flex-shrink-0" />
                      <span className="text-gray-700">{scenario}</span>
                    </li>
                  ))}
                </ul>
              </div>

              <div className="bg-red-50 border border-red-200 rounded-lg p-4">
                <div className="flex items-start">
                  <Scale className="h-5 w-5 text-red-500 mr-2 mt-0.5 flex-shrink-0" />
                  <div>
                    <h4 className="font-semibold text-red-800 mb-1">Legal Disclaimer</h4>
                    <p className="text-red-700 text-sm">{selectedStrategy.disclaimerText}</p>
                  </div>
                </div>
              </div>
            </div>

            <div className="p-6 border-t border-gray-200 bg-gray-50">
              <div className="flex justify-end space-x-3">
                <button
                  onClick={closeStrategyModal}
                  className="px-4 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50"
                >
                  Close
                </button>
                <button
                  onClick={() => {
                    // Mock download functionality
                    const content = `Strategy Information: ${selectedStrategy.name}\n\nDescription: ${selectedStrategy.description}\n\nDisclaimer: ${selectedStrategy.disclaimerText}`;
                    const blob = new Blob([content], { type: 'text/plain' });
                    const url = URL.createObjectURL(blob);
                    const a = document.createElement('a');
                    a.href = url;
                    a.download = `${selectedStrategy.name.replace(/\s+/g, '_')}.txt`;
                    a.click();
                  }}
                  className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 flex items-center"
                >
                  <Download className="h-4 w-4 mr-2" />
                  Download Information
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default IntelligentIntakePage;