import { API_CONFIG } from '../config/api';

// Compliance Utility Functions

import { 
  DisclaimerType, 
  UserRole, 
  ComplianceAction, 
  ComplianceActionPriority, 
  ComplianceActionType,
  VerificationStatus,
  LicenseStatus,
  DocumentType,
  DisclaimerConfig
} from '../types/legal-compliance';

// Disclaimer Content Templates
export const DISCLAIMER_TEMPLATES: Record<DisclaimerType, { title: string; content: string }> = {
  [DisclaimerType.NO_LEGAL_ADVICE]: {
    title: "No Legal Advice",
    content: "The information provided by this Legal AI System is for informational purposes only and does not constitute legal advice. This system provides general information about the law, but cannot provide advice about your specific legal situation. You should consult with a qualified attorney for legal advice specific to your circumstances."
  },
  [DisclaimerType.NO_ATTORNEY_CLIENT]: {
    title: "No Attorney-Client Relationship",
    content: "Use of this Legal AI System does not create an attorney-client relationship between you and the service provider or any attorney. Communications through this system are not protected by attorney-client privilege. For privileged communications, you must retain qualified legal counsel independently."
  },
  [DisclaimerType.JURISDICTION_WARNING]: {
    title: "Jurisdiction-Specific Information",
    content: "Legal information may vary significantly by jurisdiction. This system may provide information that is not applicable in your jurisdiction. Always verify legal information with local laws and qualified counsel licensed in your jurisdiction."
  },
  [DisclaimerType.AI_LIMITATION]: {
    title: "AI System Limitations",
    content: "This system uses artificial intelligence to process and analyze legal information. AI-generated content may contain errors, omissions, or outdated information. All AI-generated content must be reviewed by qualified legal professionals before use."
  },
  [DisclaimerType.ACCURACY_WARNING]: {
    title: "Information Accuracy",
    content: "While we strive for accuracy, we cannot guarantee that all information provided is current, complete, or accurate. Legal information changes frequently, and this system may not reflect the most recent developments. Always verify information with current legal sources."
  },
  [DisclaimerType.PROFESSIONAL_REVIEW]: {
    title: "Professional Review Required",
    content: "All documents, analyses, and information generated by this system require review by qualified legal professionals before use in any legal matter. Attorneys must exercise independent professional judgment when using AI-assisted tools."
  },
  [DisclaimerType.CONFIDENTIALITY_WARNING]: {
    title: "Confidentiality Notice",
    content: "Do not enter confidential or privileged information unless you understand the system's privacy and security measures. Client confidentiality obligations remain with the attorney regardless of AI assistance used."
  },
  [DisclaimerType.UPL_WARNING]: {
    title: "Unauthorized Practice of Law Warning",
    content: "Non-attorneys may not provide legal advice or represent others using information from this system. Such activities may constitute the unauthorized practice of law. Always refer legal questions to qualified attorneys."
  },
  [DisclaimerType.DATA_SECURITY]: {
    title: "Data Security Notice",
    content: "This system implements security measures to protect your data, but no system is completely secure. Be cautious about entering sensitive information. Review our Privacy Policy and security practices before use."
  },
  [DisclaimerType.BETA_DISCLAIMER]: {
    title: "Beta Version Notice",
    content: "This system is in beta testing and may contain bugs or incomplete features. Use with caution and always verify results. Features may change without notice during the beta period."
  },
  [DisclaimerType.THIRD_PARTY_CONTENT]: {
    title: "Third-Party Content",
    content: "This system may access third-party legal databases and content. We are not responsible for the accuracy or availability of third-party content. Third-party terms and conditions may apply."
  },
  [DisclaimerType.TIME_SENSITIVE]: {
    title: "Time-Sensitive Information",
    content: "Legal deadlines and time-sensitive information provided by this system should be independently verified. Missed deadlines due to system errors or delays are your responsibility."
  },
  [DisclaimerType.EMERGENCY_DISCLAIMER]: {
    title: "Emergency Legal Matters",
    content: "This system is not appropriate for emergency legal situations. If you have an urgent legal matter, contact qualified legal counsel immediately. Do not rely on this system for time-critical legal decisions."
  },
  [DisclaimerType.COMPETENCE_REQUIREMENT]: {
    title: "Professional Competence",
    content: "Attorneys using this system must maintain competence in the relevant practice areas and understand the technology being used. Competence requirements under professional conduct rules remain unchanged."
  },
  [DisclaimerType.PROFESSIONAL_RESPONSIBILITY]: {
    title: "Professional Responsibility",
    content: "Use of this system does not alter your professional responsibilities under applicable rules of professional conduct. Attorneys remain fully accountable for their professional actions and decisions."
  },
  [DisclaimerType.BILLING_TRANSPARENCY]: {
    title: "Billing and Fee Disclosure",
    content: "When using AI assistance, attorneys must consider disclosure obligations regarding billing and fees. Clients should be informed about AI assistance in their legal representation when appropriate."
  },
  [DisclaimerType.CLIENT_CONSENT]: {
    title: "Client Consent",
    content: "Attorneys may need to obtain client consent before using AI assistance, depending on jurisdiction and circumstances. Review applicable professional conduct rules regarding client consent for technology use."
  },
  [DisclaimerType.AUDIT_TRAIL]: {
    title: "Audit and Documentation",
    content: "This system maintains audit trails of your usage. Your activities may be logged for security, compliance, and professional responsibility purposes. Review our audit and logging policies."
  },
  [DisclaimerType.GENERAL_WARNING]: {
    title: "General Legal Warning",
    content: "This system is a tool to assist with legal work but cannot replace human judgment, expertise, or professional responsibility. Users remain fully responsible for all legal decisions and outcomes."
  }
};

// Role-based access control utilities
export const canUserAccessFeature = (userRole: UserRole, feature: string): boolean => {
  const rolePermissions: Record<UserRole, string[]> = {
    [UserRole.ADMIN]: ['*'], // Admin can access everything
    [UserRole.ATTORNEY]: [
      'document-analysis',
      'legal-research',
      'client-management',
      'case-management',
      'privilege-protection',
      'ai-assistance',
      'compliance-tools'
    ],
    [UserRole.PARALEGAL]: [
      'document-analysis',
      'legal-research',
      'case-management',
      'compliance-tools'
    ],
    [UserRole.CLIENT]: [
      'document-view',
      'case-status',
      'communication'
    ],
    [UserRole.PRO_SE]: [
      'document-analysis',
      'legal-information',
      'self-help-tools'
    ]
  };

  const permissions = rolePermissions[userRole] || [];
  return permissions.includes('*') || permissions.includes(feature);
};

// Compliance action priority utilities
export const getActionPriorityColor = (priority: ComplianceActionPriority): string => {
  const colors = {
    [ComplianceActionPriority.LOW]: 'text-blue-600 bg-blue-50',
    [ComplianceActionPriority.MEDIUM]: 'text-yellow-600 bg-yellow-50',
    [ComplianceActionPriority.HIGH]: 'text-orange-600 bg-orange-50',
    [ComplianceActionPriority.CRITICAL]: 'text-red-600 bg-red-50'
  };
  return colors[priority];
};

export const getActionPriorityIcon = (priority: ComplianceActionPriority): string => {
  const icons = {
    [ComplianceActionPriority.LOW]: '🔵',
    [ComplianceActionPriority.MEDIUM]: '🟡',
    [ComplianceActionPriority.HIGH]: '🟠',
    [ComplianceActionPriority.CRITICAL]: '🔴'
  };
  return icons[priority];
};

// Verification status utilities
export const getVerificationStatusColor = (status: VerificationStatus): string => {
  const colors = {
    [VerificationStatus.VERIFIED]: 'text-green-600 bg-green-50',
    [VerificationStatus.PENDING]: 'text-yellow-600 bg-yellow-50',
    [VerificationStatus.FAILED]: 'text-red-600 bg-red-50',
    [VerificationStatus.EXPIRED]: 'text-gray-600 bg-gray-50',
    [VerificationStatus.MANUAL_REVIEW]: 'text-blue-600 bg-blue-50'
  };
  return colors[status];
};

export const getLicenseStatusColor = (status: LicenseStatus): string => {
  const colors = {
    [LicenseStatus.ACTIVE]: 'text-green-600 bg-green-50',
    [LicenseStatus.INACTIVE]: 'text-gray-600 bg-gray-50',
    [LicenseStatus.SUSPENDED]: 'text-red-600 bg-red-50',
    [LicenseStatus.RETIRED]: 'text-blue-600 bg-blue-50',
    [LicenseStatus.NOT_APPLICABLE]: 'text-gray-600 bg-gray-50'
  };
  return colors[status];
};

// Compliance check utilities
export const isActionBlocking = (action: ComplianceAction): boolean => {
  const blockingActions = [
    ComplianceActionType.ACCEPT_TERMS,
    ComplianceActionType.ACCEPT_PRIVACY,
    ComplianceActionType.VERIFY_CREDENTIALS
  ];
  
  return action.isBlocking || blockingActions.includes(action.type);
};

export const getBlockingActions = (actions: ComplianceAction[]): ComplianceAction[] => {
  return actions.filter(isActionBlocking);
};

export const sortActionsByPriority = (actions: ComplianceAction[]): ComplianceAction[] => {
  const priorityOrder = {
    [ComplianceActionPriority.CRITICAL]: 4,
    [ComplianceActionPriority.HIGH]: 3,
    [ComplianceActionPriority.MEDIUM]: 2,
    [ComplianceActionPriority.LOW]: 1
  };

  return [...actions].sort((a, b) => {
    return priorityOrder[b.priority] - priorityOrder[a.priority];
  });
};

// Document type utilities
export const getDocumentTypeDisplayName = (type: DocumentType): string => {
  const displayNames = {
    [DocumentType.TERMS_OF_SERVICE]: 'Terms of Service',
    [DocumentType.PRIVACY_POLICY]: 'Privacy Policy',
    [DocumentType.ACCEPTABLE_USE_POLICY]: 'Acceptable Use Policy',
    [DocumentType.DATA_PROCESSING_AGREEMENT]: 'Data Processing Agreement',
    [DocumentType.PROFESSIONAL_SERVICES_AGREEMENT]: 'Professional Services Agreement'
  };
  return displayNames[type];
};

// Date utilities for compliance
export const isDateExpired = (dateString: string): boolean => {
  return new Date(dateString) < new Date();
};

export const getDaysUntilExpiration = (dateString: string): number => {
  const expirationDate = new Date(dateString);
  const today = new Date();
  const timeDiff = expirationDate.getTime() - today.getTime();
  return Math.ceil(timeDiff / (1000 * 3600 * 24));
};

export const formatComplianceDate = (dateString: string): string => {
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
};

// Disclaimer filtering utilities
export const getDisclaimersForRole = (disclaimers: DisclaimerConfig[], role: UserRole): DisclaimerConfig[] => {
  return disclaimers.filter(disclaimer => 
    disclaimer.isActive && 
    (disclaimer.showForRoles.length === 0 || disclaimer.showForRoles.includes(role))
  );
};

export const getDisclaimersForContext = (disclaimers: DisclaimerConfig[], context: string): DisclaimerConfig[] => {
  return disclaimers.filter(disclaimer => 
    disclaimer.isActive && 
    (disclaimer.context.length === 0 || disclaimer.context.includes(context))
  );
};

export const sortDisclaimersByPriority = (disclaimers: DisclaimerConfig[]): DisclaimerConfig[] => {
  return [...disclaimers].sort((a, b) => b.priority - a.priority);
};

// Form validation utilities
export const validateEmail = (email: string): boolean => {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
};

export const validateBarNumber = (barNumber: string, jurisdiction: string): boolean => {
  // Basic validation - in real implementation, this would use jurisdiction-specific rules
  return barNumber.length >= 3 && /^[A-Z0-9-]+$/i.test(barNumber);
};

export const validatePhoneNumber = (phone: string): boolean => {
  const phoneRegex = /^\+?[\d\s\-\(\)]{10,}$/;
  return phoneRegex.test(phone);
};

// Local storage utilities for compliance
export const setComplianceCache = (key: string, value: any): void => {
  try {
    localStorage.setItem(`compliance_${key}`, JSON.stringify({
      value,
      timestamp: Date.now()
    }));
  } catch (error) {
    console.warn('Failed to cache compliance data:', error);
  }
};

export const getComplianceCache = (key: string, maxAgeMs: number = 5 * 60 * 1000): any => {
  try {
    const cached = localStorage.getItem(`compliance_${key}`);
    if (!cached) return null;
    
    const { value, timestamp } = JSON.parse(cached);
    if (Date.now() - timestamp > maxAgeMs) {
      localStorage.removeItem(`compliance_${key}`);
      return null;
    }
    
    return value;
  } catch (error) {
    console.warn('Failed to retrieve compliance cache:', error);
    return null;
  }
};

export const clearComplianceCache = (): void => {
  try {
    const keys = Object.keys(localStorage).filter(key => key.startsWith('compliance_'));
    keys.forEach(key => localStorage.removeItem(key));
  } catch (error) {
    console.warn('Failed to clear compliance cache:', error);
  }
};

// Error handling utilities
export const getErrorMessage = (error: any): string => {
  if (typeof error === 'string') return error;
  if (error?.message) return error.message;
  if (error?.error) return error.error;
  return 'An unexpected error occurred';
};

export const isNetworkError = (error: any): boolean => {
  return error?.code === 'NETWORK_ERROR' || 
         error?.message?.includes('fetch') ||
         error?.message?.includes('network');
};

// URL utilities
export const buildApiUrl = (endpoint: string, params?: Record<string, string>): string => {
  const baseUrl = process.env.NEXT_PUBLIC_API_URL || API_CONFIG.BASE_URL;
  const url = new URL(endpoint, baseUrl);
  
  if (params) {
    Object.entries(params).forEach(([key, value]) => {
      if (value) url.searchParams.set(key, value);
    });
  }
  
  return url.toString();
};

// Cookie utilities for compliance tracking
export const setComplianceCookie = (name: string, value: string, days: number = 365): void => {
  const expires = new Date();
  expires.setTime(expires.getTime() + (days * 24 * 60 * 60 * 1000));
  document.cookie = `${name}=${value};expires=${expires.toUTCString()};path=/;secure;samesite=strict`;
};

export const getComplianceCookie = (name: string): string | null => {
  const nameEQ = name + "=";
  const cookies = document.cookie.split(';');
  
  for (let cookie of cookies) {
    cookie = cookie.trim();
    if (cookie.indexOf(nameEQ) === 0) {
      return cookie.substring(nameEQ.length);
    }
  }
  
  return null;
};

// Accessibility utilities
export const announceToScreenReader = (message: string): void => {
  const announcement = document.createElement('div');
  announcement.setAttribute('aria-live', 'polite');
  announcement.setAttribute('aria-atomic', 'true');
  announcement.className = 'sr-only';
  announcement.textContent = message;
  
  document.body.appendChild(announcement);
  
  setTimeout(() => {
    document.body.removeChild(announcement);
  }, 1000);
};

export const focusFirstError = (formId: string): void => {
  const form = document.getElementById(formId);
  if (!form) return;
  
  const errorElement = form.querySelector('[aria-invalid="true"], .error input, .error select, .error textarea');
  if (errorElement && typeof (errorElement as HTMLElement).focus === 'function') {
    (errorElement as HTMLElement).focus();
  }
};

// Debug utilities (development only)
export const logComplianceEvent = (event: string, data?: any): void => {
  if (process.env.NODE_ENV === 'development') {
    console.log(`[Compliance] ${event}`, data);
  }
};

export const logComplianceWarning = (message: string, data?: any): void => {
  if (process.env.NODE_ENV === 'development') {
    console.warn(`[Compliance Warning] ${message}`, data);
  }
};

export const logComplianceError = (message: string, error?: any): void => {
  console.error(`[Compliance Error] ${message}`, error);
};